# Generated by Django 5.1.4 on 2024-12-12 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('disability_type', models.CharField(choices=[('VI', 'Visually Impaired'), ('HI', 'Hearing Impaired'), ('MD', 'Mobility Disability'), ('OD', 'Other Disability')], max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('bank_account', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('hour_rent', models.FloatField()),
                ('city', models.CharField(choices=[('City1', 'Riyadh'), ('City2', ' Al-kharj'), ('City3', 'Al-majmaah'), ('City4', 'Afif'), ('City5', 'Jeddah'), ('City6', 'Makkah'), ('City7', 'Al-Taif'), ('City8', 'Rabigh'), ('City9', 'Al-Madinah'), ('City10', 'Dammam'), ('City11', 'Al-Ahsa'), ('City12', 'Jizan'), ('City14', 'Najran'), ('City15', 'Al-jawf'), ('City16', 'Abha'), ('City17', 'Bisha'), ('City18', 'Tabuk'), ('City19', 'Hail'), ('City20', 'Qassim')], max_length=50)),
                ('certification', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='account_app.skill')),
            ],
        ),
    ]
