# Generated by Django 5.1.4 on 2024-12-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionuser',
            name='skills',
            field=models.ManyToManyField(to='account_app.skill'),
        ),
    ]
