# Generated by Django 5.1.4 on 2024-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_disabilityuser_age_disabilityuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilityuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
