# Generated by Django 5.1.4 on 2024-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_companion_image_disabilityuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='disabilityuser',
            name='image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
