# Generated by Django 5.1.4 on 2024-12-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_companion_city_alter_skill_name'),
        ('account_app', '0007_alter_user_role'),
    ]

    operations = [
    ]
