# Generated by Django 5.1.4 on 2024-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_merge_20241216_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilityuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disabilityuser',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
