from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Booking, Payment
from account_app.models import Companion
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import get_object_or_404
import stripe
from django.conf import settings

# Create your views here.


@login_required
def book_companion_view(request, companion_id):
    companion = None
    while not companion:
        try:
            companion = Companion.objects.get(id=companion_id)
        except User.DoesNotExist:
            return redirect("booking_app:companion_list")  # Redirect if companion is not found

    if request.method == "POST":
        booking_date = request.POST.get("booking_date")
        booking_time = request.POST.get("booking_time")
        address = request.POST.get("address")

        # Combine booking date and time
        booking_date_time = timezone.datetime.strptime(
            f"{booking_date} {booking_time}", "%Y-%m-%d %H:%M"
        )

        # Save booking to the database
        booking = Booking.objects.create(
            user=request.user,
            companion=companion.companion,
            booking_date_time=booking_date_time,
            address=address,
            status="pending"
        )


        return redirect(reverse('booking_app:payment', args=[booking.id]))  # Redirect after successful booking


    context = {
        "companion": companion,
        "bookings_as_companion": Booking.objects.filter(companion=companion.id),
    }
    return render(request, "booking_app/create_booking.html", context)


@login_required
def booking_history_user_view(request):
    user_bookings = Booking.objects.filter(user=request.user)
    context = {
        "user_bookings": user_bookings,
    }
    return render(request, "booking_app/user_booking_history.html", context)

@login_required
def booking_history_companion_view(request):
    try:
        companion = Companion.objects.get(companion=request.user)
    except Companion.DoesNotExist:
        
        messages.error(request, "You can't access this page.")
        return redirect('booking_app:companion_list')

    companion_bookings = Booking.objects.filter(companion=companion.companion)

    if request.method == 'POST':
        booking_id = request.POST.get('booking_id')
        action = request.POST.get('action')
        try:
            booking = Booking.objects.get(id=booking_id)

            if action == 'accept':
                booking.status = 'CONFIRMED'
                
            elif action == 'reject':
                booking.status = 'CANCELLED'
                
            booking.save()
            
            return redirect('booking_app:booking_history_companion')

        except Booking.DoesNotExist:
            messages.error(request, "The booking you're trying to modify does not exist.")
            return redirect('booking_app:booking_history_companion')

    context = {
        "companion_bookings": companion_bookings,
    }
    return render(request, 'booking_app/companion_booking_history.html', context)




def companion_list_view(request):
    """
    View to list all available companions.
    Users can select a companion to book from this list.
    """
    companions = Companion.objects.filter(availability=True)
    return render(request, 'booking_app/companion_list.html', {'companions': companions})

stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required
def payment_view(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    companion = booking.companion.compinon_user
    amount = int(companion.hour_rent * 100)  # Convert to halalas (Stripe requires this)

    if request.method == "POST":
        token = request.POST.get("stripeToken")  # Stripe's generated token for the card
        card_name = request.POST.get("card_name")

        try:
            # Create a charge with Stripe
            charge = stripe.Charge.create(
                amount=amount,
                currency="SAR",
                description=f"Payment for booking {booking.id}",
                source=token,  # Token generated by Stripe.js
            )

            # Save the payment in your database
            Payment.objects.create(
                booking=booking,
                status="completed",
                
            )

            # Update booking status
            booking.status = "CONFIRMED"
            booking.save()

            messages.success(request, "Payment successful!")
            return redirect("booking_app:booking_history_user")

        except stripe.error.StripeError as e:
            messages.error(request, f"Payment failed: {e}")
            return redirect("booking_app:payment", booking_id=booking.id)

    context = {
        "booking": booking,
        "amount": amount / 100,  # Convert back to dollars for display
        "stripe_public_key": settings.STRIPE_PUBLIC_KEY,
    }
    return render(request, "booking_app/payment.html", context)