# Generated by Django 5.1.4 on 2024-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_booking_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
