# Generated by Django 5.1.4 on 2024-12-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_alter_companion_certification'),
        ('booking_app', '0003_booking_end_booking_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_companion', to='account_app.companion'),
        ),
    ]
