# Generated by Django 5.1.4 on 2024-12-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], max_length=1)),
                ('comment', models.TextField()),
                ('disability_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.disabilityuser')),
            ],
        ),
    ]
