# Generated by Django 5.1.4 on 2024-12-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_companion_city_alter_skill_name'),
        ('booking_app', '0003_booking_end_booking_date_time'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.booking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='companion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account_app.companion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='disability_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.disabilityuser'),
        ),
    ]
